In [2]:
import numpy as np

arr = np.arange(16).reshape((4,4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
# 첫번째 행 선택

print ( arr[[0],])
print ( arr[0:1,])

[[0 1 2 3]]
[[0 1 2 3]]


In [ ]:
# 마지막열 전체
print( arr[:,[3]]) # 앞에는 생략 불가능 
print( arr[:,3:4])

[[ 3]
 [ 7]
 [11]
 [15]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [9]:
print (arr[[0,-1],:][:,[0,-1]])
print(arr[[0,-1],:])
print(arr[:,[0,-1]])


[[ 0  3]
 [12 15]]
[[ 0  1  2  3]
 [12 13 14 15]]
[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]]


In [ ]:
#첫번째 행과 마지막 행만 선택, 각행의 첫번째, 마지막열 선택 
print (arr[[0,-1]][:,[0,-1]]) # 리스트끼리 곱의 개념 
# 0, -1 x 
print (arr[[0,3],:][:,[0,3]])
print()
print( arr[::3,::3])
print()
print (arr[0::])




[[ 0  3]
 [12 15]]
[[ 0  3]
 [12 15]]

[[ 0  3]
 [12 15]]

[[ 0  1  2  3]
 [12 13 14 15]]

[[ 0  1  2  3]
 [12 13 14 15]]


**오답**

```
print (arr[[0,-1]][[0,-1]])
```

> 위와 같이 출력하면 아래와 같이 나오기 때문에 뒤의 1열 4열 전체값을 잡아줘야 한다
출력 (0,0) , (-1,-1)

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
```
해서 첫번째 행과 마지막행 전체와 첫번째열 마지막열 전체를 불러와야 한다.
정리해보면 아래와 같다

 print (arr[[0,-1],:][:,[0,-1]])
 이것을 풀어보면 
 ---
 arr 
 
 [[첫번째행, 마지막행], ':' # 열 전체] 
 x 
 [':' # 행전체 [첫번째열, 마지막열]]

---
```
[[ 0  1  2  3]
 [12 13 14 15]]
x
[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]]

 =
 [[ 0  3]
 [12 15]]
```

In [20]:
# 짝수 인덱스 행(0번째, 2번째 행), 홀수 인덱스 열(1,3) 선택

# arr[[0,2],:][:,[1,3]]
arr[::2, 1::2] #[시작인덱스 전체/ 끝인덱스 전체/ 2 간격, 시작인덱스 1번째, 끝인덱스 전체 / 3 간격 ]

array([[ 1,  3],
       [ 9, 11]])

In [27]:
#위의 3차원 행렬을 작성하세요
arr3 = np.arange(144).reshape((4,6,6))
arr3

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35]],

       [[ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107]],

       [[108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137],
        [138, 139, 140, 141, 142, 143]]])

In [36]:
arr4 = np.stack([np.arange(36).reshape((6,6))]*4)

for i in range(4):
    arr4[i,0,0] = i

arr4

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 1,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 2,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 3,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [40]:

# 2번째 층(깊이, 면) 선택
arr4[1]

array([[ 1,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [57]:
#모든 층, 네번째 행, 두번째 열 원소 선택, 1차원 배열로 작성

arr4[:,3,1] # 괄호를 안넣으면 1차원 배열 형식이라 1차원으로 나옴
arr4[:,[3],[1]].reshape(-1)

array([19, 19, 19, 19])

In [61]:
#배열의 첫 두 층, 마지막 두 행, 마지막 두 열 선택
arr4[:2,4::,4::] , arr4[:2,-2:,-2:]

(array([[[28, 29],
         [34, 35]],
 
        [[28, 29],
         [34, 35]]]),
 array([[[28, 29],
         [34, 35]],
 
        [[28, 29],
         [34, 35]]]))

In [66]:
#세번째 층, 두번째 행에서 네번째 행, 홀수 인덱스 열
arr4[3,1:4,1::2]

array([[ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])