In [3]:
import numpy as np

arr = np.arange(16).reshape((4,4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
# 첫번째 행 선택

print ( arr[[0],])
print ( arr[0:1,])

[[0 1 2 3]]
[[0 1 2 3]]


In [18]:
# 마지막열 전체
print( arr[:,[3]]) # 앞에는 생략 불가능 
ㅔ
print( arr[:,3:4])

[[ 3]
 [ 7]
 [11]
 [15]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [41]:
#첫번째 행과 마지막 행만 선택, 각행의 첫번째, 마지막열 선택 
print (arr[[0,-1]][:,[0,-1]]) # 리스트끼리 곱의 개념 
# 0, -1 x 
print (arr[[0,3]][:,[0,3]])
print()
print( arr[::3,::3])
print()
print (arr[0::])




[[ 0  3]
 [12 15]]
[[ 0  3]
 [12 15]]

[[ 0  3]
 [12 15]]

[[ 0  1  2  3]
 [12 13 14 15]]

[[ 0  1  2  3]
 [12 13 14 15]]


**오답**

```
print (arr[[0,-1]][[0,-1]])
```

> 위와 같이 출력하면 아래와 같이 나오기 때문에 뒤의 1열 4열 전체값을 잡아줘야 한다
출력 (0,0) , (-1,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])